schema_version = "1.0.0"

# Example of manifest file for a Blender extension
# Change the values according to your extension
id = "strange_attractors"
version = "2.1.0"
name = "Stranger Attractors"
tagline = "Add Strange Attractor curves"
maintainer = "7bitretro <justinh73@gmail.com.com>"
# Supported types: "add-on", "theme"
type = "add-on"

# Optional link to documentation, support, source files, etc
# website = "https://github.com/Googyflip/strangeattractors"

# Optional list defined by Blender and server, see:
# https://docs.blender.org/manual/en/dev/advanced/extensions/tags.html
tags = ["Add Curve"]

blender_version_min = "3.6.0"
# # Optional: Blender version that the extension does not support, earlier versions are supported.
# # This can be omitted and defined later on the extensions platform if an issue is found.
# blender_version_max = "5.1.0"

# License conforming to https://spdx.org/licenses/ (use "SPDX: prefix)
# https://docs.blender.org/manual/en/dev/advanced/extensions/licenses.html
license = [
  "SPDX:GPL-2.0-or-later",
]
